# Generated by Django 4.2.1 on 2023-05-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('std_email', models.CharField(max_length=100, unique=True)),
                ('std_age', models.IntegerField()),
                ('std_address', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('studentid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentid')),
            ],
            options={
                'ordering': ['std_name'],
            },
        ),
    ]
