# Generated by Django 4.2.1 on 2023-05-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_subject_studentmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmarks',
            options={'ordering': ['student__std_name']},
        ),
    ]
